spring.application.name=shoes_f_management

spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.url=jdbc:postgresql://localhost:5432/shoesfdb
spring.datasource.username=postgres
spring.datasource.password=Manuel2309lm6
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


